import test from 'node:test';import assert from 'node:assert/strict';import {canonical,digest,sha256Text,createRng,defineGame,compileCartridge,createRun,availability,legalActions,dispatch,project,createReplay,createReplayCursor,verifyReplay,solve,LudotapeError,clone} from '../src/index.mjs';import {createMemoryRepository,createStorageRepository} from '../src/storage.mjs';import {createDraft} from '../src/editor.mjs';import warehouse from '../examples/warehouse-circuit.mjs';import cards from '../examples/card-duel.mjs';
const counter=defineGame({id:'counter',version:'1',initialState:()=>({n:0}),actions:s=>s.n<3?[{type:'inc'}]:[],transition:s=>({n:s.n+1}),isGoal:s=>s.n===3,project:s=>({label:String(s.n)})});const cart=compileCartridge(counter,{title:'x'});
test('canonical sorts object keys',()=>assert.equal(canonical({b:1,a:2}),'{"a":2,"b":1}'));
test('canonical retains array order',()=>assert.equal(canonical([2,1]),'[2,1]'));
test('canonical normalizes negative zero',()=>assert.equal(canonical(-0),'0'));
test('canonical encodes unicode strings',()=>assert.equal(canonical('🎮'),'"🎮"'));
test('canonical rejects NaN',()=>assert.throws(()=>canonical(NaN),/Non-finite/));
test('canonical rejects Infinity',()=>assert.throws(()=>canonical(Infinity),/Non-finite/));
test('canonical rejects undefined',()=>assert.throws(()=>canonical({x:undefined}),/Unsupported/));
test('canonical rejects functions',()=>assert.throws(()=>canonical(()=>0),/Unsupported/));
test('canonical rejects cycles',()=>{const x={};x.x=x;assert.throws(()=>canonical(x),/Cycle/)});
test('canonical rejects Date objects',()=>assert.throws(()=>canonical(new Date()),/Non-plain/));
test('SHA-256 empty vector',()=>assert.equal(sha256Text(''),'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'));
test('SHA-256 abc vector',()=>assert.equal(sha256Text('abc'),'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'));
test('object digest is canonical',()=>assert.equal(digest({a:1,b:2}),digest({b:2,a:1})));
test('digest changes with content',()=>assert.notEqual(digest({a:1}),digest({a:2})));
test('clone deeply separates objects',()=>{const x={a:{b:1}},y=clone(x);y.a.b=2;assert.equal(x.a.b,1)});
test('RNG equal seeds match',()=>{const a=createRng(42),b=createRng(42);assert.deepEqual([a.next(),a.next()],[b.next(),b.next()])});
test('RNG distinct seeds differ',()=>assert.notEqual(createRng(1).next(),createRng(2).next()));
test('RNG int is bounded',()=>{const r=createRng(3);for(let i=0;i<100;i++)assert.ok(r.int(7)>=0&&r.int(7)<7)});
test('RNG rejects invalid bound',()=>assert.throws(()=>createRng().int(0),/positive integer/));
test('RNG picks collection members',()=>assert.ok(['a','b'].includes(createRng(8).pick(['a','b']))));
test('RNG rejects empty pick',()=>assert.throws(()=>createRng().pick([]),/empty/));
test('defineGame requires id',()=>assert.throws(()=>defineGame({version:'1',initialState(){},actions(){}}),/id/));
test('defineGame requires version',()=>assert.throws(()=>defineGame({id:'x',initialState(){},actions(){}}),/version/));
test('defineGame requires initialState',()=>assert.throws(()=>defineGame({id:'x',version:'1',actions(){}}),/initialState/));
test('defineGame requires actions',()=>assert.throws(()=>defineGame({id:'x',version:'1',initialState(){}}),/actions/));
test('defineGame requires transition',()=>assert.throws(()=>defineGame({id:'x',version:'1',initialState(){},actions(){}}),/transition/));
test('defined game is frozen',()=>assert.ok(Object.isFrozen(counter)));
test('cartridge has format marker',()=>assert.equal(cart.format,'ludotape/cartridge@1'));
test('same rules and document have same identity',()=>assert.equal(cart.identity,compileCartridge(counter,{title:'x'}).identity));
test('document changes cartridge identity',()=>assert.notEqual(cart.identity,compileCartridge(counter,{title:'y'}).identity));
test('version changes cartridge identity',()=>{const g=defineGame({...counter,version:'2'});assert.notEqual(cart.identity,compileCartridge(g,{title:'x'}).identity)});
test('run starts with empty separate journal',()=>{const r=createRun(cart);assert.deepEqual(r.journal,[]);assert.deepEqual(r.state,{n:0})});
test('availability returns legal actions',()=>assert.deepEqual(availability(createRun(cart)),[{type:'inc'}]));
test('legalActions aliases availability',()=>assert.deepEqual(legalActions(createRun(cart)),[{type:'inc'}]));
test('dispatch advances state',()=>{const r=createRun(cart);dispatch(r,{type:'inc'});assert.equal(r.state.n,1)});
test('dispatch appends journal hashes',()=>{const r=createRun(cart),e=dispatch(r,{type:'inc'});assert.equal(r.journal.length,1);assert.equal(e.after,digest({n:1}))});
test('dispatch rejects illegal action',()=>assert.throws(()=>dispatch(createRun(cart),{type:'dec'}),e=>e instanceof LudotapeError&&e.code==='E_ILLEGAL_ACTION'));
test('actions stop at terminal state',()=>{const r=createRun(cart);for(let i=0;i<3;i++)dispatch(r,{type:'inc'});assert.deepEqual(availability(r),[])});
test('projection uses game projector',()=>assert.deepEqual(project(createRun(cart)),{label:'0'}));
test('projection accepts adapter',()=>assert.equal(project(createRun(cart),v=>v.label),'0'));
test('replay captures all turns',()=>{const r=createRun(cart);dispatch(r,{type:'inc'});assert.equal(createReplay(r).actions.length,1)});
test('valid replay verifies',()=>{const r=createRun(cart);dispatch(r,{type:'inc'});assert.equal(verifyReplay(cart,createReplay(r)).ok,true)});
test('tampered action fails replay',()=>{const r=createRun(cart);dispatch(r,{type:'inc'});const p=createReplay(r);p.actions[0]={type:'bad'};assert.equal(verifyReplay(cart,p).ok,false)});
test('tampered checkpoint fails replay',()=>{const r=createRun(cart);dispatch(r,{type:'inc'});const p=createReplay(r);p.checkpoints[0]='0'.repeat(64);assert.equal(verifyReplay(cart,p).error.code,'E_CHECKPOINT')});
test('foreign cartridge fails replay',()=>{const r=createRun(cart),p=createReplay(r);assert.equal(verifyReplay(compileCartridge(counter,{other:1}),p).error.code,'E_IDENTITY')});
test('BFS solves counter',()=>{const s=solve(cart,{maxDepth:4});assert.equal(s.status,'solved');assert.equal(s.depth,3)});
test('BFS respects depth bound',()=>assert.notEqual(solve(cart,{maxDepth:2}).status,'solved'));
test('BFS solves Warehouse Circuit',()=>{const s=solve(warehouse,{maxDepth:4});assert.equal(s.status,'solved');assert.deepEqual(s.actions.map(a=>a.direction),['down','right'])});
test('Warehouse has renderer-neutral grid projection',()=>assert.equal(project(createRun(warehouse)).kind,'grid'));
test('Card Duel repeats from same seed',()=>assert.deepEqual(createRun(cards,{seed:99}).state,createRun(cards,{seed:99}).state));
test('Card Duel differs across seeds',()=>assert.notDeepEqual(createRun(cards,{seed:1}).state.deck,createRun(cards,{seed:2}).state.deck));
test('Card action is playable and journaled',()=>{const r=createRun(cards,{seed:4});dispatch(r,availability(r)[0]);assert.equal(r.state.round,1);assert.equal(r.journal.length,1)});
test('Card Duel replay verifies after RNG transitions',()=>{const r=createRun(cards,{seed:4});dispatch(r,availability(r)[0]);dispatch(r,availability(r)[0]);assert.equal(verifyReplay(cards,createReplay(r)).ok,true)});
test('memory repository round trip is isolated',async()=>{const r=createMemoryRepository(),v={x:1};await r.put('a',v);v.x=2;assert.deepEqual(await r.get('a'),{x:1})});
test('memory repository sorted prefix list',async()=>{const r=createMemoryRepository();await r.put('p/b',2);await r.put('p/a',1);await r.put('q',3);assert.deepEqual(await r.list('p/'),['p/a','p/b'])});
test('memory repository delete',async()=>{const r=createMemoryRepository();await r.put('x',1);assert.equal(await r.delete('x'),true);assert.equal(await r.get('x'),null)});
test('storage repository works with Storage contract',async()=>{const m=new Map(),s={get length(){return m.size},key:i=>[...m.keys()][i],getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};const r=createStorageRepository(s);await r.put('x',{a:1});assert.deepEqual(await r.get('x'),{a:1});assert.deepEqual(await r.list(),['x'])});
test('draft replace increments revision',()=>{const d=createDraft({x:1});d.replace({x:2});assert.equal(d.revision,1);assert.equal(d.document.x,2)});
test('draft update receives clone',()=>{const d=createDraft({x:1});d.update(x=>({...x,x:3}));assert.equal(d.document.x,3)});
test('draft undo restores content',()=>{const d=createDraft({x:1});d.replace({x:2});assert.equal(d.undo(),true);assert.equal(d.document.x,1)});
test('draft snapshot digest matches document',()=>{const d=createDraft({x:1}),s=d.snapshot();assert.equal(s.digest,digest(s.document))});
test('draft markSaved clears dirty flag',()=>{const d=createDraft({x:1});d.replace({x:2});d.markSaved();assert.equal(d.dirty,false)});
test('defineGame rejects a non-function isGoal',()=>assert.throws(()=>defineGame({id:'bad-goal',version:'1',initialState:()=>({}),actions:()=>[],transition:s=>s,isGoal:true}),error=>error.code==='E_GAME'));
test('replay cursor steps and verifies incrementally',()=>{const source=createRun(cart);dispatch(source,{type:'inc'});dispatch(source,{type:'inc'});const cursor=createReplayCursor(cart,createReplay(source));assert.equal(cursor.turn,0);assert.equal(cursor.done,false);assert.equal(cursor.step().index,0);assert.equal(cursor.turn,1);assert.equal(cursor.stepAll().length,1);assert.equal(cursor.done,true);assert.equal(cursor.verify().ok,true);assert.throws(()=>cursor.step(),error=>error.code==='E_CURSOR_DONE')});
test('replay cursor leaves its run unchanged on checkpoint mismatch',()=>{const source=createRun(cart);dispatch(source,{type:'inc'});const replay=createReplay(source);replay.checkpoints[0]='0'.repeat(64);const cursor=createReplayCursor(cart,replay);assert.throws(()=>cursor.step(),error=>error.code==='E_CHECKPOINT');assert.equal(cursor.turn,0);assert.equal(cursor.run.turn,0);assert.deepEqual(cursor.run.state,{n:0})});
