import {CORE_TEMPLATE_VERSION} from './constants.mjs';

/**
 * Render the source of a generated custom `ICore` implementation for a document-driven
 * counter cartridge format `<id>/cartridge@1`. Self-contained (does not delegate to the
 * built-in JS/TS core) so it doubles as a starting point for real custom-format cores.
 * Deterministic; depends only on `{id, name}`.
 */
export function coreTemplate({id, name}) {
  const cartridgeFormat = `${id}/cartridge@1`;
  return `// Generated by \`ludotape-create-core\`. A minimal, working ICore implementation for a
// document-driven counter cartridge format: '${cartridgeFormat}'.
//
// This core is intentionally self-contained: it does NOT delegate to the built-in JS/TS core.
// Copy/adapt the sections marked TODO to interpret your own cartridge format.
import {canonical, digest, deepFreeze, clone, createRng, LudotapeError} from 'ludotape';
// Running from a source checkout without an installed dependency? Use a relative import instead:
// import {canonical, digest, deepFreeze, clone, createRng, LudotapeError} from '../../src/index.mjs';

const CARTRIDGE_FORMAT = ${JSON.stringify(cartridgeFormat)};
const CORE_ID = ${JSON.stringify(id)};
const CORE_VERSION = ${JSON.stringify(CORE_TEMPLATE_VERSION)};
const CORE_NAME = ${JSON.stringify(name)};

const bad = (code, message, details) => { throw new LudotapeError(code, message, details); };

// TODO: replace this with a real interpreter for your cartridge format's authoring document.
// Here, the "document" is just {target: number} and the rules are hardcoded (increment a
// counter until it reaches target).
function compileDocument(document) {
  const doc = clone(document ?? {});
  if (typeof doc.target !== 'number' || !Number.isSafeInteger(doc.target) || doc.target < 0) {
    bad('E_CORE_CARTRIDGE', 'document.target must be a non-negative safe integer');
  }
  deepFreeze(doc);
  const identity = digest({format: CARTRIDGE_FORMAT, document: doc});
  return Object.freeze({format: CARTRIDGE_FORMAT, identity, document: doc});
}

// Runs are opaque frozen handles backed by a private WeakMap -- callers can only interact with
// them through the core's methods, matching the encapsulation style of the reference core.
const RUNS = new WeakMap();
function runData(run) {
  const found = RUNS.get(run);
  if (!found) bad('E_CORE', 'valid run required');
  return found;
}
function makeRun(cartridge, seed, state, rngState, turn, journal, initialDigest) {
  const run = Object.freeze({});
  RUNS.set(run, {cartridge, seed: clone(seed), state: clone(state), rngState: rngState >>> 0, turn, journal: clone(journal), initialDigest});
  return run;
}
function sameAction(a, b) { return canonical(a) === canonical(b); }

export function createCore() {
  const core = {
    metadata: deepFreeze({
      format: 'ludotape/core@1',
      id: CORE_ID,
      version: CORE_VERSION,
      name: CORE_NAME,
      description: 'Document-driven counter core generated by ludotape-create-core.',
      capabilities: {replay: true, rewind: true, solve: true, scenarios: true},
      cartridgeFormats: [CARTRIDGE_FORMAT]
    }),

    // Accepts an already-compiled cartridge (frozen, matching format/identity), OR a module
    // namespace / plain object providing a 'document' or 'default' authoring document.
    // TODO: accept whatever source shapes make sense for your own tooling.
    loadCartridge(source) {
      if (source && typeof source === 'object' && source.format === CARTRIDGE_FORMAT && typeof source.identity === 'string' && Object.isFrozen(source)) {
        return source;
      }
      const document = source && typeof source === 'object' ? (source.document ?? source.default ?? source) : undefined;
      if (!document || typeof document !== 'object') bad('E_CORE_CARTRIDGE', 'unrecognized cartridge source');
      return compileDocument(document);
    },

    createRun(cartridge, {seed = 0} = {}) {
      if (!cartridge?.identity || cartridge.format !== CARTRIDGE_FORMAT) bad('E_CORE_CARTRIDGE', 'compiled cartridge required');
      const rng = createRng(seed); // TODO: consume rng.* here if your rules need randomness.
      const state = {count: 0};
      return makeRun(cartridge, seed, state, rng.state, 0, [], digest(state));
    },

    availability(run) {
      const d = runData(run);
      return d.state.count < d.cartridge.document.target ? [{type: 'increment'}] : [];
    },

    dispatch(run, action) {
      const d = runData(run);
      const legal = core.availability(run);
      if (!legal.some(x => sameAction(x, action))) bad('E_ILLEGAL_ACTION', 'action is not currently available', {action: clone(action), legal});
      if (action?.type !== 'increment') bad('E_ILLEGAL_ACTION', 'unsupported action', {action: clone(action)});
      const before = digest(d.state);
      const next = {count: d.state.count + 1};
      const entry = deepFreeze({index: d.turn, action: clone(action), before, after: digest(next), rngBefore: d.rngState, rngAfter: d.rngState});
      d.state = next; d.turn++; d.journal.push(entry);
      return deepFreeze(clone(entry));
    },

    project(run, adapter) {
      const d = runData(run);
      const view = deepFreeze({count: d.state.count, target: d.cartridge.document.target, complete: d.state.count === d.cartridge.document.target});
      if (!adapter) return view;
      const info = deepFreeze({cartridge: {identity: d.cartridge.identity}, seed: clone(d.seed), turn: d.turn, stateDigest: digest(d.state)});
      return adapter(view, info);
    },

    isGoal(run) {
      const d = runData(run);
      return d.state.count === d.cartridge.document.target;
    },

    createReplay(run) {
      const d = runData(run);
      return clone({format: 'ludotape/replay@1', cartridge: d.cartridge.identity, seed: d.seed, initial: d.initialDigest, actions: d.journal.map(x => x.action), checkpoints: d.journal.map(x => x.after), final: digest(d.state)});
    },

    verifyReplay(cartridge, replayObj) {
      try {
        if (replayObj.cartridge !== cartridge.identity) bad('E_IDENTITY', 'cartridge identity mismatch');
        const run = core.createRun(cartridge, {seed: replayObj.seed});
        if (runData(run).initialDigest !== replayObj.initial) bad('E_INITIAL', 'initial state mismatch');
        for (let i = 0; i < replayObj.actions.length; i++) {
          const entry = core.dispatch(run, replayObj.actions[i]);
          if (replayObj.checkpoints[i] !== entry.after) bad('E_CHECKPOINT', \`checkpoint \${i} mismatch\`);
        }
        if (digest(runData(run).state) !== replayObj.final) bad('E_FINAL', 'final state mismatch');
        return {ok: true, turns: runData(run).turn, final: replayObj.final, run};
      } catch (error) {
        return {ok: false, error: {code: error.code ?? 'E_UNKNOWN', message: error.message}};
      }
    },

    rewindRun(run, turns = 1) {
      const d = runData(run);
      if (!Number.isSafeInteger(turns) || turns < 0 || turns > d.turn) bad('E_CORE', 'turns must be a safe integer from 0 to the run turn');
      const target = d.turn - turns;
      const rebuilt = core.createRun(d.cartridge, {seed: d.seed});
      for (let i = 0; i < target; i++) core.dispatch(rebuilt, d.journal[i].action);
      return rebuilt;
    },

    // TODO: this brute-force walk is fine for a tiny counter; replace with a real search
    // strategy (see src/index.mjs's solve()) for richer cartridge formats.
    solve(cartridge, options = {}) {
      const maxNodes = options.maxNodes ?? 1000;
      const run = core.createRun(cartridge, {seed: options.seed ?? 0});
      const actions = [];
      let visited = 0;
      while (!core.isGoal(run)) {
        if (visited++ >= maxNodes) return {status: 'bounded', actions: null, visited};
        const [action] = core.availability(run);
        if (!action) return {status: 'unsolved', actions: null, visited};
        core.dispatch(run, action);
        actions.push(action);
      }
      return {status: 'solved', actions, visited};
    }
  };
  return Object.freeze(core);
}

export default createCore();
`;
}
