/**
 * Render the next-steps snippet `create-game.mjs` prints to stdout after scaffolding.
 * Deterministic; depends only on the given fields.
 */
export function gameReadmeSnippet({name, id, dir, fileName, scenariosFileName}) {
  return `Next steps for ${name} (${id}):

  node bin/ludotape.mjs validate ${dir}/${fileName}
  node bin/ludotape.mjs check ${dir}/${fileName} 0 2 100
  node bin/ludotape.mjs test ${dir}/${fileName} ${dir}/${scenariosFileName}
  node bin/ludotape.mjs solve ${dir}/${fileName} 0 3 100
`;
}

/**
 * Render `README.md` content for a generated custom core directory. Deterministic; depends
 * only on the given fields.
 */
export function coreReadmeTemplate({id, name, dir}) {
  return `# ${name}

A minimal \`ICore\` implementation for the document-driven counter cartridge format
\`${id}/cartridge@1\`, generated by \`ludotape-create-core\`.

## Files

- \`core.mjs\` -- the core implementation (exports \`createCore\` and a default instance).
- \`core.manifest.json\` -- core manifest (\`ludotape/core-manifest@1\`).
- \`sample-cartridge.mjs\` -- a sample authoring document for smoke-testing the core.

## Validate (static, no gameplay execution)

\`\`\`sh
node devkit/validate-core.mjs ${dir}
\`\`\`

## Conformance (runs the core through a real lifecycle)

\`\`\`sh
node bin/ludotape.mjs core conformance ${dir} ${dir}/sample-cartridge.mjs
\`\`\`

## Adapting this core to your own format

Edit \`core.mjs\`: replace \`compileDocument\`, \`availability\`, \`dispatch\`, and \`project\` with
logic for your own cartridge format. Keep all state/actions/projections canonical (see
\`canonical()\` from \`ludotape\`) and use \`context.rng\`/seeded RNG rather than \`Math.random\`
or \`Date.now\` for any state-affecting randomness. See CORE_SPEC.md and
docs/custom-core-reference.md for the full ICore contract.

## Troubleshooting

- **\`E_CORE_MANIFEST\` diagnostics** -- check \`core.manifest.json\` matches the format above
  exactly: no unknown keys, \`entry\` starting with \`./\`, and all four \`capabilities\` booleans.
- **\`E_CORE_METADATA\` diagnostics** -- \`core.mjs\`'s \`metadata\` must match the manifest's
  \`id\`/\`version\`/\`name\`/\`capabilities\`/\`cartridgeFormats\` exactly.
- **\`E_CORE_SHAPE\` diagnostics** -- a required method is missing, or a declared capability
  (e.g. \`replay\`) is missing its required method(s).
`;
}
